const CONFIG = {
  API_URL: "https://script.google.com/macros/s/AKfycbwxbXZiq3OIoeUSdSM7h8Y3zusw1H48Nit_3g5ire0TlvHepRtIgm10Oj7yRVrfbxhB/exec",
  APP_NAME: "VLC Cloud Launcher",
  APP_TAGLINE: "Save once. Open anywhere.",
  VERSION: "1.0.0",
  CACHE_KEY: "vlc_cloud_launcher_streams",
  CACHE_EXPIRY: 5 * 60 * 1000,
  DEFAULT_CATEGORIES: [
    "All",
    "Movies",
    "Sports",
    "Anime",
    "Series",
    "TV",
    "Music",
    "Kids",
    "Live",
    "Other",
  ],
  CATEGORY_COLORS: {
    Movies: "#E53935",
    Sports: "#1E88E5",
    Anime: "#8E24AA",
    Series: "#7E57C2",
    TV: "#FB8C00",
    Music: "#43A047",
    Kids: "#00ACC1",
    Live: "#F4511E",
    Other: "#546E7A",
  },
  TOAST_DURATION: 3000,
  DEBOUNCE_DELAY: 300,
  PAGINATION: {
    DESKTOP: 20,
    MOBILE: 10,
  },
};
